DROP DATABASE IF EXISTS game;
CREATE DATABASE game DEFAULT CHARACTER SET utf8;
USE game;

CREATE TABLE IF NOT EXISTS game_phone(
  id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'phone id',
  content VARCHAR(20) NOT NULL DEFAULT '' COMMENT 'content'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT 'ganme phone table'