DROP DATABASE IF EXISTS tspringmvc;
CREATE DATABASE tspringmvc DEFAULT CHARACTER SET utf8;
USE tspringmvc;

CREATE TABLE IF NOT EXISTS tspringmvc_phone(
  id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'phone id',
  content VARCHAR(20) NOT NULL DEFAULT '' COMMENT 'content'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT 'tspringmvc phone table'